### ISSUE TITLE
[low priority] Rename repo to better reflect purpose

### ISSUE THREAD

**Issue by diwakergupta** [hirosystems/stacks-e2e-testing#42]
This repo now has tests for both 2.1 and 2.2. Opening this is as a low-priority issue for later: repo name should better reflect its purpose, given it'll likely be heavily used for the next hard-fork as well.

**Comment by diwakergupta** [comment]
I'm thinking we should rename this sooner rather than later. Another consideration if this repo would better belong in the `stacks-network`, and even somewhere under the `stacks-blockchain` repo. 

Thoughts @obycode @friedger @kantai @lgalabru @saralab

**Comment by friedger** [comment]
`stacks-blockchain` has integration tests in rust, therefore, I think, these devnet-js tests are better as a separate repo.

It should also inspire developer to test their contracts with devnet-js

Name: `stacks-blockchain-devnet-testing`

**Comment by kantai** [comment]
I agree that these tests should be considered useful examples for other developers to test their contracts with devnet-js, but I'd also like to see these tests end up in the `stacks-blockchain` repository -- we'd have to figure out how to structure their placement there (i.e., could be a top-level `/testing/` directory), but I think it'd be great to integrate devnet-js testing into that repo's CI.

**Comment by friedger** [comment]
As a non-rust developer, I am scared to explore `stacks-blockchain` repo. If it is clear from the top-level that js developers can benefit, then one mono-repo might work.

**Comment by friedger** [comment]
Once done, this should be part of https://github.com/friedger/awesome-stacks-chain

**Comment by obycode** [comment]
I renamed to `stacks-e2e-testing`.

**Comment by obycode** [comment]
I don't know what procedure to follow to decide if it should move inside the stacks-blockchain repo. I think that can be opened as an issue on that repo if desired.
